/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dreamchase_android_six_JNITest */

#ifndef _Included_cn_dreamchase_android_six_JNITest
#define _Included_cn_dreamchase_android_six_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dreamchase_android_six_JNITest
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_dreamchase_android_six_JNITest_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
